#include<stdio.h>
#include<conio.h>
#include<math.h>
void main(void)
{
float num1=1.0,num2=1.0;
int k,a,b,c,d,e,count;
double total,p,A;
long float a,b,c,x1,x2;
printf("Enter the number for selecting the program");
printf("1 for Calculator\n 2 for Marksheet\n 3 for Quadratic formula\n 4 for Tables");
scanf("%d",&k);
if(a==1)
{
{
char op;
0.0==0.0&&0.0==0.0;
while(!(num1==0.0&&num2==0.0))
{
clrscr();
printf("Type number,operator,number\n");
scanf("%f  %c  %f",&num1,&op,&num2);
switch(op)
{
case '+':
printf("the addition of two number =%f",num1+num2);//5.0
break;
case '-':
printf("the subtraction of two number =%f",num1-num2);
break;
case '*':
printf("the multiplication of two number =%f",num1*num2);
break;
case '/':
printf("the division of two number =%f",num1/num2);
break;
default:
printf("Unknown operator");
}
printf("\n \n");
}
getch();
}
}
if(a==2)
{
{
clrscr();
printf("Enter marks obtained in Chemistry\n");
scanf("%d",&a);
printf("Enter marks obtained in Mathematics\n");
scanf("%d",&b);
printf("Enter marks obtained in Physics\n");
scanf("%d",&c);
printf("Enter marks obtained in Islamiyaat\n");
scanf("%d",&d);
printf("Enter marks obtained in English\n");
clrscr();
printf("\t\tSIR SYED UNIVERSITY OF ENGINEERING AND TECHNOLOGY\n\n");
printf("Name:Aazib Ahmed Ansari\n");
printf("ROLL NO: 2017-EE-07562\n");
printf("\nSUBJECTS\tMARKS");
printf("\nChemistry\t100");
printf("\nMathematics\t100");
printf("\nPhysics\t\t100");
printf("\nIslamiyaat\t100");
printf("\nEnglish\t\t100");
total=a+b+c+d+e;
printf("\ntotal=%lf",total);
p=total*100/500;
printf("\npercentage=%lf",p);
{
if(p>=70&&p<=90)
printf("\nA",p);
else
if(p>=50&&p<=60)
printf("\nB",p);
else
printf("\nfailed");
}
getch();
}
}
if(a==3)
{
{
clrscr();
long float a,b,c,x1,x2;
double x=(b*b)-(4*a*c),result;
a=1,b=2,c=1;
result=sqrt(x);
printf("Enter a,b,c %lf %lf %lf");
printf("The square root is %lf %lf %lf is %lf\n",x,result);
scanf("%lf %lf %lf %lf",&a,&b,&c);
x1=(-1*b+x)/2*a;
x2=(-1*b-x)/2*a;
printf("the answer  is %lf",x1,x2);
getch();
}
}
if(a==4)
{

	{
	int count;
	count=1;
	while(count<=10);
	{
	printf("\n2*%d=%d   	3*%d=%d",count,2*count,count,3*count);
	count++;
	getch();
	}
	}
}
}